# Aula — Join das Tabelas 5 (2012 e 2026) com a Tabela 1.1.1 do IBGE (2022)

Nesta atividade vamos:

1. Carregar as duas **Tabelas 5**, referentes à composição da desocupação por sexo em **2012** e **2026**.
2. Juntar as duas tabelas usando `Sigla`, `Código` e `Estado`.
3. Preparar a **Tabela 1.1.1 do IBGE (2022)**, usando a aba `2022` do arquivo Excel.
4. Cruzar as três tabelas pelo nome da Unidade da Federação (`Estado`).
5. Calcular algumas diferenças para facilitar a comparação entre os anos.

> Os arquivos utilizados estão no mesmo ZIP desta atividade.

In [1]:
import pandas as pd

In [2]:
# Arquivos da atividade
arquivo_2012 = r"H:\python\atividades\GitNovo\AtividadeJoin\Tabela5-sem_emprego_2012.csv"
arquivo_2026 = r"H:\python\atividades\GitNovo\AtividadeJoin\Tabela5-sem_emprego_2026.csv"
arquivo_ibge = r"H:\python\atividades\GitNovo\AtividadeJoin\Tabela 1.1.1.xlsx"

# Leitura das Tabelas 5
t2012 = pd.read_csv(arquivo_2012, sep=";", decimal=",")
t2026 = pd.read_csv(arquivo_2026, sep=";", decimal=",")

print("Tabela 2012:")
display(t2012.head())

print("Tabela 2026:")
display(t2026.head())

Tabela 2012:

,Sigla,Código,Estado,Desocupados - homens (2012 T1),Desocupados - mulheres (2012 T1)
0,AC,12,Acre,45.3,54.7
1,AL,27,Alagoas,44.7,55.3
2,AM,13,Amazonas,47.5,52.5
3,AP,16,Amapá,48.1,51.9
4,BA,29,Bahia,43.8,56.2

Tabela 2026:

,Sigla,Código,Estado,Desocupados - homens (2026 T1),Desocupados - mulheres (2026 T1)
0,AC,12,Acre,53.2,46.8
1,AL,27,Alagoas,50.7,49.3
2,AM,13,Amazonas,46.8,53.2
3,AP,16,Amapá,51.1,48.9
4,BA,29,Bahia,44.7,55.3

## 1. Juntando as duas Tabelas 5

A junção segue o modelo solicitado na aula:

```python
t2012.merge(t2026, on=["Sigla", "Código", "Estado"], how="inner")
```

Assim, cada Unidade da Federação fica em uma única linha, com os valores de 2012 e 2026.

In [2]:
# Join das Tabelas 5
comp = t2012.merge(
    t2026,
    on=["Sigla", "Código", "Estado"],
    how="inner"
)

# Reorganizando as colunas
comp = comp[
    [
        "Sigla", "Código", "Estado",
        "Desocupados - homens (2012 T1)",
        "Desocupados - mulheres (2012 T1)",
        "Desocupados - homens (2026 T1)",
        "Desocupados - mulheres (2026 T1)"
    ]
]

print(f"Quantidade de UFs após o join: {len(comp)}")
display(comp)

Quantidade de UFs após o join: 27

   Sigla  ...  Desocupados - mulheres (2026 T1)
0     AC  ...                              46.8
1     AL  ...                              49.3
2     AM  ...                              53.2
3     AP  ...                              48.9
4     BA  ...                              55.3
5     CE  ...                              47.3
6     DF  ...                              52.1
7     ES  ...                              52.5
8     GO  ...                              52.5
9     MA  ...                              50.9
10    MG  ...                              51.4
11    MS  ...                              54.7
12    MT  ...                              57.2
13    PA  ...                              51.7
14    PB  ...                              51.1
15    PE  ...                              51.3
16    PI  ...                              44.9
17    PR  ...                              53.7
18    RJ  ...                              54.6
19    RN  ...                              51.8
20    RO  ...                              67.0
21    RR  ...                              56.6
22    RS  ...                              52.6
23    SC  ...                              55.4
24    SE  ...                              59.7
25    SP  ...                              53.8
26    TO  ...                              53.8

[27 rows x 7 columns]

In [3]:
# Diferenças entre 2026 e 2012
comp["Variação homens (p.p.)"] = (
    comp["Desocupados - homens (2026 T1)"]
    - comp["Desocupados - homens (2012 T1)"]
)

comp["Variação mulheres (p.p.)"] = (
    comp["Desocupados - mulheres (2026 T1)"]
    - comp["Desocupados - mulheres (2012 T1)"]
)

display(comp)

   Sigla  Código  ... Variação homens (p.p.)  Variação mulheres (p.p.)
0     AC      12  ...                    7.9                      -7.9
1     AL      27  ...                    6.0                      -6.0
2     AM      13  ...                   -0.7                       0.7
3     AP      16  ...                    3.0                      -3.0
4     BA      29  ...                    0.9                      -0.9
5     CE      23  ...                    1.6                      -1.6
6     DF      53  ...                    6.9                      -6.9
7     ES      32  ...                    1.1                      -1.1
8     GO      52  ...                    6.5                      -6.5
9     MA      21  ...                    1.9                      -1.9
10    MG      31  ...                    5.5                      -5.5
11    MS      50  ...                   -1.9                       1.9
12    MT      51  ...                   -1.3                       1.3
13    PA      15  ...                    5.1                      -5.1
14    PB      25  ...                    4.5                      -4.5
15    PE      26  ...                    4.8                      -4.8
16    PI      22  ...                    3.9                      -3.9
17    PR      41  ...                    6.0                      -6.0
18    RJ      33  ...                    1.2                      -1.2
19    RN      24  ...                   -2.8                       2.8
20    RO      11  ...                  -10.4                      10.4
21    RR      14  ...                    1.6                      -1.6
22    RS      43  ...                    4.6                      -4.6
23    SC      42  ...                    1.9                      -1.9
24    SE      28  ...                   -6.2                       6.2
25    SP      35  ...                    0.8                      -0.8
26    TO      17  ...                   -9.1                       9.1

[27 rows x 9 columns]

## 2. Preparando a Tabela 1.1.1 do IBGE

A planilha Excel possui várias abas. Para esta atividade usamos a aba **`2022`**, que contém o número médio de horas semanais dedicadas aos cuidados de pessoas e/ou afazeres domésticos.

Como a tabela tem cabeçalhos em várias linhas, vamos localizar os dados a partir da linha em que aparecem as Unidades da Federação. Serão mantidas:

- `Estado`
- `Horas - total`
- `Horas - homem branco`
- `Horas - homem preto ou pardo`
- `Horas - mulher branca`
- `Horas - mulher preta ou parda`

A coluna `Horas - total` representa o número médio de horas semanais da população de 14 anos ou mais.

In [4]:
# Leitura da aba 2022 sem cabeçalho para podermos tratar os títulos da tabela
ibge_raw = pd.read_excel(arquivo_ibge, sheet_name="2022", header=None)

# Os dados começam na linha 8 (índice 8)
ibge = ibge_raw.iloc[8:, [0, 1, 4, 5, 6, 7]].copy()

ibge.columns = [
    "Estado",
    "Horas - total",
    "Horas - homem branco",
    "Horas - homem preto ou pardo",
    "Horas - mulher branca",
    "Horas - mulher preta ou parda"
]

# Retira linhas que não são UFs
ufs = set(comp["Estado"])
ibge = ibge[ibge["Estado"].isin(ufs)].copy()

# Converte os valores para número
colunas_horas = [c for c in ibge.columns if c != "Estado"]
for coluna in colunas_horas:
    ibge[coluna] = pd.to_numeric(ibge[coluna], errors="coerce")

ibge = ibge.reset_index(drop=True)

print(f"Quantidade de UFs na Tabela 1.1.1: {len(ibge)}")
display(ibge)

Quantidade de UFs na Tabela 1.1.1: 27

                 Estado  ...  Horas - mulher preta ou parda
0              Rondônia  ...                      21.061410
1                  Acre  ...                      16.710754
2              Amazonas  ...                      20.716986
3               Roraima  ...                      16.560244
4                  Pará  ...                      21.591144
5                 Amapá  ...                      15.908487
6             Tocantins  ...                      19.629399
7              Maranhão  ...                      20.739589
8                 Piauí  ...                      23.695440
9                 Ceará  ...                      24.952274
10  Rio Grande do Norte  ...                      24.422884
11              Paraíba  ...                      24.035650
12           Pernambuco  ...                      24.243396
13              Alagoas  ...                      25.856637
14              Sergipe  ...                      25.637681
15                Bahia  ...                      23.217119
16         Minas Gerais  ...                      23.075751
17       Espírito Santo  ...                      22.196626
18       Rio de Janeiro  ...                      20.957728
19            São Paulo  ...                      21.767620
20               Paraná  ...                      19.365380
21       Santa Catarina  ...                      19.646573
22    Rio Grande do Sul  ...                      19.107720
23   Mato Grosso do Sul  ...                      19.542761
24          Mato Grosso  ...                      18.695923
25                Goiás  ...                      19.587913
26     Distrito Federal  ...                      19.307332

[27 rows x 6 columns]

## 3. Cruzando as três tabelas

Agora usamos o resultado das duas Tabelas 5 (`comp`) e fazemos um novo `merge` com a Tabela 1.1.1 do IBGE.

A chave de cruzamento é `Estado`, pois a Tabela 1.1.1 não possui as colunas `Sigla` e `Código` presentes nas Tabelas 5.

In [5]:
# Cruzamento das três tabelas
cruzado = comp.merge(
    ibge,
    on="Estado",
    how="inner"
)

# Colunas em uma ordem mais fácil de ler
cruzado = cruzado[
    [
        "Sigla", "Código", "Estado",
        "Desocupados - homens (2012 T1)",
        "Desocupados - mulheres (2012 T1)",
        "Desocupados - homens (2026 T1)",
        "Desocupados - mulheres (2026 T1)",
        "Variação homens (p.p.)",
        "Variação mulheres (p.p.)",
        "Horas - total",
        "Horas - homem branco",
        "Horas - homem preto ou pardo",
        "Horas - mulher branca",
        "Horas - mulher preta ou parda"
    ]
]

print(f"Quantidade de UFs no cruzamento final: {len(cruzado)}")
display(cruzado)

Quantidade de UFs no cruzamento final: 27

   Sigla  Código  ... Horas - mulher branca  Horas - mulher preta ou parda
0     AC      12  ...             16.130352                      16.710754
1     AL      27  ...             24.093655                      25.856637
2     AM      13  ...             18.764969                      20.716986
3     AP      16  ...             16.648579                      15.908487
4     BA      29  ...             22.572730                      23.217119
5     CE      23  ...             23.019718                      24.952274
6     DF      53  ...             17.738123                      19.307332
7     ES      32  ...             20.464462                      22.196626
8     GO      52  ...             18.440842                      19.587913
9     MA      21  ...             19.881056                      20.739589
10    MG      31  ...             22.186650                      23.075751
11    MS      50  ...             18.593200                      19.542761
12    MT      51  ...             17.782825                      18.695923
13    PA      15  ...             19.835110                      21.591144
14    PB      25  ...             23.642936                      24.035650
15    PE      26  ...             23.357880                      24.243396
16    PI      22  ...             20.494063                      23.695440
17    PR      41  ...             18.896661                      19.365380
18    RJ      33  ...             19.203741                      20.957728
19    RN      24  ...             23.547080                      24.422884
20    RO      11  ...             20.412887                      21.061410
21    RR      14  ...             16.135877                      16.560244
22    RS      43  ...             18.868230                      19.107720
23    SC      42  ...             19.414764                      19.646573
24    SE      28  ...             21.740902                      25.637681
25    SP      35  ...             20.771186                      21.767620
26    TO      17  ...             19.663713                      19.629399

[27 rows x 14 columns]

## 4. Comparação ano a ano

Abaixo podemos observar as mudanças na composição da desocupação por sexo entre 2012 e 2026.

A variação é calculada em **pontos percentuais (p.p.)**:

`valor de 2026 - valor de 2012`.

In [6]:
comparacao = cruzado[
    [
        "Sigla", "Estado",
        "Desocupados - homens (2012 T1)",
        "Desocupados - homens (2026 T1)",
        "Variação homens (p.p.)",
        "Desocupados - mulheres (2012 T1)",
        "Desocupados - mulheres (2026 T1)",
        "Variação mulheres (p.p.)"
    ]
].copy()

display(comparacao.sort_values("Variação mulheres (p.p.)", ascending=False))

   Sigla  ... Variação mulheres (p.p.)
20    RO  ...                     10.4
26    TO  ...                      9.1
24    SE  ...                      6.2
19    RN  ...                      2.8
11    MS  ...                      1.9
12    MT  ...                      1.3
2     AM  ...                      0.7
25    SP  ...                     -0.8
4     BA  ...                     -0.9
7     ES  ...                     -1.1
18    RJ  ...                     -1.2
21    RR  ...                     -1.6
5     CE  ...                     -1.6
9     MA  ...                     -1.9
23    SC  ...                     -1.9
3     AP  ...                     -3.0
16    PI  ...                     -3.9
14    PB  ...                     -4.5
22    RS  ...                     -4.6
15    PE  ...                     -4.8
13    PA  ...                     -5.1
10    MG  ...                     -5.5
1     AL  ...                     -6.0
17    PR  ...                     -6.0
8     GO  ...                     -6.5
6     DF  ...                     -6.9
0     AC  ...                     -7.9

[27 rows x 8 columns]

## 5. Cruzamento com as horas de cuidados e afazeres domésticos

Para facilitar a leitura do resultado final, selecionamos as variáveis de desocupação e as horas semanais do IBGE.

In [7]:
resultado_final = cruzado[
    [
        "Sigla", "Estado",
        "Desocupados - homens (2012 T1)",
        "Desocupados - mulheres (2012 T1)",
        "Desocupados - homens (2026 T1)",
        "Desocupados - mulheres (2026 T1)",
        "Variação homens (p.p.)",
        "Variação mulheres (p.p.)",
        "Horas - total",
        "Horas - homem branco",
        "Horas - homem preto ou pardo",
        "Horas - mulher branca",
        "Horas - mulher preta ou parda"
    ]
].copy()

display(resultado_final)

   Sigla  ... Horas - mulher preta ou parda
0     AC  ...                     16.710754
1     AL  ...                     25.856637
2     AM  ...                     20.716986
3     AP  ...                     15.908487
4     BA  ...                     23.217119
5     CE  ...                     24.952274
6     DF  ...                     19.307332
7     ES  ...                     22.196626
8     GO  ...                     19.587913
9     MA  ...                     20.739589
10    MG  ...                     23.075751
11    MS  ...                     19.542761
12    MT  ...                     18.695923
13    PA  ...                     21.591144
14    PB  ...                     24.035650
15    PE  ...                     24.243396
16    PI  ...                     23.695440
17    PR  ...                     19.365380
18    RJ  ...                     20.957728
19    RN  ...                     24.422884
20    RO  ...                     21.061410
21    RR  ...                     16.560244
22    RS  ...                     19.107720
23    SC  ...                     19.646573
24    SE  ...                     25.637681
25    SP  ...                     21.767620
26    TO  ...                     19.629399

[27 rows x 13 columns]

## 6. Exportando o resultado

Por fim, o resultado do cruzamento das três tabelas é salvo em CSV, usando `;` como separador, conforme o exemplo da aula.

In [8]:
# Salvar o resultado final
arquivo_saida = "geral.csv"
resultado_final.to_csv(arquivo_saida, sep=";", decimal=",", index=False, encoding="utf-8-sig")

print(f"Arquivo salvo: {arquivo_saida}")

Arquivo salvo: geral.csv